"use client";

import { useMemo, useState } from "react";

import type { DashboardData, EvidenceJob, Skill } from "@/lib/types";

type View = "Briefing" | "Role intelligence" | "Skill terrain" | "Field comparison" | "Method trail";
const views: View[] = ["Briefing", "Role intelligence", "Skill terrain", "Field comparison", "Method trail"];

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
function Panel({ className = "", children }: { className?: string; children: React.ReactNode }) { return <section className={`intel-panel ${className}`}>{children}</section>; }
function SectionHead({ label, title, note }: { label: string; title: string; note?: string }) { return <header className="section-head"><Eyebrow>{label}</Eyebrow><h2>{title}</h2>{note && <p>{note}</p>}</header>; }

function SourceTrail({ data }: { data: DashboardData }) {
  return <Panel className="source-trail"><SectionHead label="SOURCE TRAIL / 01" title="Traceable, bounded evidence" /><div className="trail-steps"><div><b>01</b><span>Original sample fixture</span></div><div><b>02</b><span>Python clean + map</span></div><div><b>03</b><span>SQLite aggregate</span></div><div><b>04</b><span>Static JSON artifact</span></div></div><p>{data.overview.source.disclosure}</p></Panel>;
}

function SignalList({ skills, compact = false }: { skills: Skill[]; compact?: boolean }) {
  return <div className={compact ? "signal-list compact" : "signal-list"}>{skills.map((item, index) => <div key={item.skill}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.skill}</strong><i style={{ "--signal": `${Math.max(22, (item.posting_count / (skills[0]?.posting_count || 1)) * 100)}%` } as React.CSSProperties} /><b>{item.posting_count}</b></div>)}</div>;
}

function EvidenceCard({ job, index }: { job: EvidenceJob; index: number }) {
  return <article className="evidence-card"><div className="evidence-meta"><span>OBS-{String(index + 1).padStart(2, "0")}</span><span>{job.posted_at || "UNDATED"}</span></div><h3>{job.title}</h3><p>{job.company || "Employer withheld"} · {job.location || "Location withheld"}</p><div>{job.roles.split(" | ").map((role) => <span key={role}>{role}</span>)}</div></article>;
}

function RoleSkillMatrix({ data, selectedRole }: { data: DashboardData; selectedRole?: string }) {
  const roles = Object.entries(data.roleSkills.roles);
  const skills = Array.from(new Set(roles.flatMap(([, items]) => items.map((item) => item.skill)))).slice(0, 12);
  const visibleRoles = selectedRole ? roles.filter(([role]) => role === selectedRole) : roles;
  const counts = new Map(roles.flatMap(([, items]) => items.map((item) => [item.skill, item.posting_count])));
  return <Panel className="matrix-panel"><SectionHead label="ROLE–SKILL TERRAIN / 02" title={selectedRole ? `${selectedRole} skill surface` : "Skill presence across mapped roles"} note="Cell intensity is a Python-generated posting count." /><div className="matrix-scroll"><div className="matrix" style={{ gridTemplateColumns: `minmax(155px, 1.35fr) repeat(${skills.length}, minmax(44px, .55fr))` }}><div className="matrix-corner">ROLE / SKILL</div>{skills.map((skill) => <div className="matrix-skill" key={skill}>{skill}</div>)}{visibleRoles.map(([role, items]) => { const map = new Map(items.map((item) => [item.skill, item.posting_count])); return <><div className="matrix-role" key={`${role}-label`}>{role}<span>{data.overview.role_comparison.find((item) => item.role === role)?.posting_count ?? 0} postings</span></div>{skills.map((skill) => { const value = map.get(skill) ?? 0; const max = counts.get(skill) ?? 1; return <div key={`${role}-${skill}`} className={value ? "matrix-cell filled" : "matrix-cell"} style={{ "--heat": value ? String(0.22 + (value / max) * 0.72) : "0" } as React.CSSProperties} aria-label={`${role}, ${skill}: ${value} postings`}><span>{value || "·"}</span></div>; })}</>; })}</div></div></Panel>;
}

export function Dashboard({ data }: { data: DashboardData }) {
  const [view, setView] = useState<View>("Briefing");
  const [selectedRole, setSelectedRole] = useState(Object.keys(data.roleSkills.roles)[0] ?? "");
  const [skillsInput, setSkillsInput] = useState("");
  const snapshot = new Intl.DateTimeFormat("en", { year: "numeric", month: "short", day: "2-digit" }).format(new Date(data.overview.generated_at));
  return <div className="workspace-shell min-h-[100dvh]">
    <aside className="command-rail"><div className="rail-brand"><span>SA</span><div><strong>SkillAtlas</strong><small>INTELLIGENCE WORKSPACE</small></div></div><div className="rail-scope"><Eyebrow>OPERATING SCOPE</Eyebrow><p>INDONESIA<br />JOB-MARKET<br />EVIDENCE</p><span>SNAPSHOT / {snapshot.toUpperCase()}</span></div><nav aria-label="Intelligence views">{views.map((item, index) => <button className={view === item ? "rail-link selected" : "rail-link"} key={item} onClick={() => setView(item)}><span>{String(index + 1).padStart(2, "0")}</span>{item}</button>)}</nav><div className="rail-footer"><span className="live-mark" />STATIC ARTIFACT<br /><small>PIPELINE VERIFIED</small></div></aside>
    <main className="workspace-main"><header className="workspace-top"><div><Eyebrow>SKILLATLAS / MARKET OBSERVATION LAYER</Eyebrow><h1>{view}</h1></div><div className="top-context"><span>DATA CONDITION</span><strong>READ-ONLY · TRACEABLE</strong></div></header>
      {view === "Briefing" && <Briefing data={data} />}
      {view === "Role intelligence" && <RoleIntelligence data={data} selectedRole={selectedRole} onRoleChange={setSelectedRole} />}
      {view === "Skill terrain" && <SkillTerrain data={data} />}
      {view === "Field comparison" && <FieldComparison data={data} selectedRole={selectedRole} onRoleChange={setSelectedRole} entered={skillsInput} onEnteredChange={setSkillsInput} />}
      {view === "Method trail" && <MethodTrail data={data} />}
    </main>
  </div>;
}

function Briefing({ data }: { data: DashboardData }) { const featured = data.evidence.jobs.slice(0, 3); return <>
  <section className="briefing-grid"><div className="briefing-lead"><Eyebrow>ANALYST BRIEFING / 2026.02</Eyebrow><h2>Skills converge around <em>{data.overview.kpis.top_observed_skill}</em>; role context changes the surrounding toolchain.</h2><p>This workspace exposes the observed evidence layer behind an Indonesian job-description sample. It is designed to make source, method, and uncertainty legible before any interpretation.</p><div className="briefing-facts"><span>{data.overview.kpis.matched_postings}<small>MAPPED POSTINGS</small></span><span>{data.overview.kpis.roles_covered}<small>ROLE LENSES</small></span><span>{data.clusters.clusters.length}<small>EXPLORATORY GROUPS</small></span></div></div><SourceTrail data={data} /></section>
  <section className="briefing-asym"><Panel className="signal-panel"><SectionHead label="DOMINANT SIGNALS / 03" title="Repeatedly named capabilities" note="Frequency preserves evidence, not importance." /><SignalList skills={data.overview.top_skills.slice(0, 8)} /></Panel><Panel className="analyst-panel"><SectionHead label="ANALYST NOTE / 04" title="Read the counts with restraint" /><p>Role counts are multi-label by design. A posting can contribute to more than one role where the title explicitly signals ambiguity.</p><p>The included sample is deliberately small. It demonstrates a reproducible investigation, not a market-wide conclusion.</p><div className="analyst-signoff"><span>ASSESSMENT STATUS</span><strong>DESCRIPTIVE ONLY</strong></div></Panel></section>
  <section className="evidence-section"><SectionHead label="EVIDENCE LEDGER / 05" title="Recent source records" note="Cleaned posting fields retained for inspection." /><div className="evidence-grid">{featured.map((job, index) => <EvidenceCard key={job.job_id} job={job} index={index} />)}</div></section>
</>; }

function RoleIntelligence({ data, selectedRole, onRoleChange }: { data: DashboardData; selectedRole: string; onRoleChange: (value: string) => void }) { const jobs = data.evidence.jobs.filter((job) => job.roles.split(" | ").includes(selectedRole)); return <>
  <section className="dossier-top"><div><Eyebrow>ROLE DOSSIER / SELECTOR</Eyebrow><h2>Interrogate one role without losing its evidence trail.</h2></div><label className="command-select"><span>ACTIVE ROLE</span><select value={selectedRole} onChange={(event) => onRoleChange(event.target.value)}>{Object.keys(data.roleSkills.roles).map((role) => <option key={role}>{role}</option>)}</select></label></section><RoleSkillMatrix data={data} selectedRole={selectedRole} /><section className="role-dossier-grid"><Panel><SectionHead label="CAPABILITY SEQUENCE" title="Observed requirement order" /><SignalList skills={data.roleSkills.roles[selectedRole] ?? []} compact /></Panel><Panel className="role-evidence"><SectionHead label="EVIDENCE FRAGMENTS" title="Matched posting records" />{jobs.length ? jobs.map((job, index) => <EvidenceCard key={job.job_id} job={job} index={index} />) : <p className="empty-copy">No evidence rows for this role in the bundled sample.</p>}</Panel></section>
</>; }

function SkillTerrain({ data }: { data: DashboardData }) { return <><section className="terrain-intro"><div><Eyebrow>ROLE–SKILL MATRIX / COMMAND VIEW</Eyebrow><h2>See overlap before you segment.</h2></div><p>Each cell preserves the role-specific summary made by the Python pipeline. Empty cells are absent dictionary matches, not proof of irrelevance.</p></section><RoleSkillMatrix data={data} /><section className="cluster-field"><SectionHead label="EXPLORATORY TERRAIN / 06" title="Co-occurring skill ecosystems" note="KMeans is an investigative aid, not a taxonomy." /><div>{data.clusters.clusters.map((cluster) => <article key={cluster.id}><span>GROUP {String(cluster.id + 1).padStart(2, "0")}</span><h3>{cluster.label}</h3><p>{cluster.posting_count} records align with this exploratory pattern.</p><div>{cluster.defining_skills.map((skill) => <i key={skill}>{skill}</i>)}</div></article>)}</div></section></>; }

function FieldComparison({ data, selectedRole, onRoleChange, entered, onEnteredChange }: { data: DashboardData; selectedRole: string; onRoleChange: (value: string) => void; entered: string; onEnteredChange: (value: string) => void }) { const target = data.roleSkills.roles[selectedRole] ?? []; const input = useMemo(() => new Set(entered.split(",").map((item) => item.trim().toLowerCase()).filter(Boolean)), [entered]); const matched = target.filter((item) => input.has(item.skill.toLowerCase())); const missing = target.filter((item) => !input.has(item.skill.toLowerCase())); const coverage = target.length ? Math.round((matched.length / target.length) * 100) : 0; return <><section className="comparison-lead"><div><Eyebrow>FIELD COMPARISON / RULE-BASED</Eyebrow><h2>Position your named skills against the observed role surface.</h2><p>This is an exact-label comparison with a precomputed Python result. It does not infer proficiency, recommend a career move, or store your input.</p></div><label className="command-select"><span>REFERENCE ROLE</span><select value={selectedRole} onChange={(event) => onRoleChange(event.target.value)}>{Object.keys(data.roleSkills.roles).map((role) => <option key={role}>{role}</option>)}</select></label></section><section className="input-console"><label htmlFor="skills"><span>ENTER CANONICAL SKILLS</span><input id="skills" value={entered} onChange={(event) => onEnteredChange(event.target.value)} placeholder="Python, SQL, Docker" /></label><p>Use comma-separated labels found in the role dossier. Matching is case-insensitive and exact.</p></section><section className="comparison-grid"><Panel className="coverage-reading"><Eyebrow>ALIGNMENT SIGNAL</Eyebrow><strong>{coverage}<small>%</small></strong><p>{matched.length} of {target.length} displayed labels match your input.</p><div className="coverage-rule"><i style={{ width: `${coverage}%` }} /></div></Panel><Panel><SectionHead label="PRESENT" title="Matched labels" /><TokenCloud items={matched} empty="No exact labels are present yet." positive /></Panel><Panel><SectionHead label="NOT PRESENT" title="Observed labels to inspect" /><TokenCloud items={missing} empty="All displayed labels are present." /></Panel></section></>; }
function TokenCloud({ items, empty, positive = false }: { items: Skill[]; empty: string; positive?: boolean }) { return items.length ? <div className={positive ? "token-cloud positive" : "token-cloud"}>{items.map((item) => <span key={item.skill}>{item.skill}<b>{item.posting_count}</b></span>)}</div> : <p className="empty-copy">{empty}</p>; }

function MethodTrail({ data }: { data: DashboardData }) { return <><section className="method-intro"><Eyebrow>METHOD TRAIL / AUDITABLE BY DESIGN</Eyebrow><h2>The web layer is an observation room, not the analytical engine.</h2><p>Every visible figure originates in the local Python pipeline then travels into versioned JSON artifacts. No browser-side job extraction, role mapping, SQL aggregation, or clustering is performed.</p></section><SourceTrail data={data} /><section className="method-records"><MethodRecord number="01" title="Dataset boundary" text={`${data.overview.source.name}. It is an illustrative fixture, included to make the investigation reproducible without scraping or accounts.`} /><MethodRecord number="02" title="Analytical engine" text="Pandas cleaning, title mapping, regex dictionary extraction, SQLite aggregation, and deterministic exploratory clustering run in Python." /><MethodRecord number="03" title="Role semantics" text="One posting may map to multiple roles where its title is explicitly ambiguous. Counts are transparent multi-label observations." /><MethodRecord number="04" title="Limitations" text="A small source, finite dictionary, and weak clustering quality constrain generalization. Treat the product as an evidence viewer, not a forecast." /></section></>; }
function MethodRecord({ number, title, text }: { number: string; title: string; text: string }) { return <article><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>; }
